### ISSUE TITLE
Commands + Chance

### ISSUE THREAD

**Issue by Lorenzostuy** [Th3Shadowbroker/OuroborosMines#49]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I'd like the following feature implemented to this plugin

Commands with reward chance (Configurable & multiple commands)
https://gyazo.com/93dea2d3b42dad87b9d05a397d19da35

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Th3Shadowbroker** [comment]
- [ ] Check way of implementation
- [ ] Implement feature
- [ ] Dev.-Testing
- [ ] Friendly User test

**Comment by Th3Shadowbroker** [comment]
@Lorenzostuy a new test build is ready. Commands can be configured [as described](https://github.com/Th3Shadowbroker/OuroborosMines/wiki/Drop-groups#execute-commands). The test build of this feature is available [here](https://jenkins.th3shadowbroker.org/job/OuroborosMines/17/). Please let me know if everything works as expected.

**Comment by Lorenzostuy** [comment]
>.... [11:39:47 ERROR]: Could not pass event BlockBreakEvent to OuroborosMines v1.9.3-SNAPSHOT
java.lang.IllegalArgumentException: Cannot drop a Null item.
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:749) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at dev.th3shadowbroker.ouroboros.mines.listeners.BlockBreakListener.breakBlock(BlockBreakListener.java:129) ~[?:?]
at dev.th3shadowbroker.ouroboros.mines.listeners.BlockBreakListener.onBlockBreak(BlockBreakListener.java:114) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor394.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:310) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:270) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1475) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1194) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1187) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1163) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1007) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Th3Shadowbroker** [comment]
Thanks for the log!
I fixed the problem in B[uild 18](https://jenkins.th3shadowbroker.org/job/OuroborosMines/18/) 👍🏼

**Comment by Th3Shadowbroker** [comment]
Feature has been fully implemented in #52 and included in the full rewrite of the drop system #53.
